import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";

import "@/app/globals.css";
import NextAuthWrapper from "@/library/next.auth.wrapper";
import Layout from "@/components/layout/client/layout";
import { ModalProvider } from "@/context/QuickViewModalContext";
import { ReduxProvider } from "@/redux/provider";
import { PreviewSliderProvider } from "@/context/PreviewSliderContext";
import QuickViewModal from "@/components/screen/toyota/quick-view-modal.comp";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "dPCoP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          defer
          data-site="YOUR_DOMAIN_HERE"
          src="https://api.nepcha.com/js/nepcha-analytics.js"
        ></script>
        <link rel="shortcut icon" href="/favicon.png" type="image/png" />
      </head>
      <body className={roboto.className}>
        <ReduxProvider>
          <ModalProvider>
            <PreviewSliderProvider>
              <Layout>
                <AntdRegistry>
                  <NextAuthWrapper>
                    {children}
                    <QuickViewModal />
                  </NextAuthWrapper>
                </AntdRegistry>
              </Layout>
            </PreviewSliderProvider>
          </ModalProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
